//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultimate_Analysis_Application
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatsTest
    {
        public int ID { get; set; }
        public string Player_Name { get; set; }
        public int Points_Played { get; set; }
        public int C___ { get; set; }
        public int Offensive_Points { get; set; }
        public int Defensive_Points { get; set; }
        public double Offensive_Efficiency { get; set; }
        public double Defensive_Efficiency { get; set; }
    }
}
